# VORTEX Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vortex-dev

resources:
  - namespace.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - core/deployment.yaml
  - core/service.yaml
  - core/configmap.yaml
  - worker/deployment.yaml
  - ui/deployment.yaml
  - ui/service.yaml

commonLabels:
  app.kubernetes.io/part-of: vortex-gen-3
  app.kubernetes.io/managed-by: kustomize
